---
title: "Estimating subnational family planning indicators for married women with custom user data"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
options(warn=-1)
```


```{r, message = FALSE}
library(fpemlocal)
```
## Introduction
1. [Fit a one country model](#fit) `fit_fp_c`
2. [Calculate point estimates for indicators](#results) `calc_fp_c`
3. [Plot the  point estimates against the survey data](#plot) `plot_fp_c`

## <a name="fit"></a>
## 1. Fit a one country model
```{r}
fit <- fit_fp_c(
  surveydata_filepath = "data-raw/manuscript_example_data/afghanistan_4_married_example.csv",
  division_numeric_code = 4,
  is_in_union = "Y",
  first_year = 1970,
  last_year = 2030,
  subnational = TRUE
)
```

## <a name="results"></a>
## 2. Calculate point estimates for indicators
```{r}
population_data <- read.csv("data-raw/manuscript_example_data/afghanistan_4_married_popdata_example.csv")
results <- calc_fp_c(fit = fit,
                     population_data = population_data)
```

## <a name="plot"></a>
## 3. Plot estimates and survey data
```{r}
plot_fp_c(
  fit,
  results,
  indicators = c(
    "unmet_need_any",
    "contraceptive_use_modern",
    "contraceptive_use_traditional",
    "contraceptive_use_any"
    )
  )
```
